project_id = "wbbqfihwrteyabzyqdfi"

[functions.create-doku-payment]
verify_jwt = true

[functions.doku-payment-notification]
verify_jwt = false

[functions.check-doku-payment-status]
verify_jwt = false
