project_id = "wbbqfihwrteyabzyqdfi"

[functions.chatbot]
verify_jwt = false

[functions.create-doku-payment]
verify_jwt = true

[functions.doku-payment-notification]
verify_jwt = false

[functions.check-doku-payment-status]
verify_jwt = false

[functions.translate-game-content]
verify_jwt = false

[functions.translate-news-content]
verify_jwt = false

[functions.download-game]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false
